### ISSUE TITLE
Code organisation

### ISSUE THREAD

**Issue by Alawrence01** [Error404CU/ALL-Project-2#3]
Program code needs to be organised into classes.

**Comment by iRaduxD** [comment]
class Robot(object):
    def **init**(self, x, y, size = 5, speed = 10, color = "black"):
        self.x = x
        self.y = y
        self.size = size
        self.speed = speed
        self.color = color
    def drawRobot(self, canvas):
        self.canvas = canvas
        self.shape = canvas.create_rectangle(self.x, self.y, self.x + self.size, self.y + self.size, fill = self.color)
    def moveRobot(self, a, b):
        self.a = a
        self.b = b
        self.x += self.a
        self.y += self.b
        self.canvas.coords(self.shape, self.x, self.y, self.x + self.size, self.y + self.size)
        self.canvas.update()

**Comment by iRaduxD** [comment]
class Landmark(object):
    def **init**(self, x, y, size = 30, color = 'black', t = 0):
        self.x = x
        self.y = y
        self.size = size
        self.color = color
        self.t = t
    def drawLandmark(self, canvas):
        self.canvas = canvas
        canvas.shape = canvas.create_rectangle(self.x, self.y, self.x + self.size, self.y + self.size, fill = self.color)
        self.canvas.update()
